### ISSUE TITLE
fix missing SAGE data

### ISSUE THREAD

**Issue by maxheld83** [subugoe/hoad#197]
@jhoeffler just reported this on teams:

> Und jetzt auch das neue. Habt Ihr SAGE rausgenommen, weil da so viele Informationen fehlten?

**Comment by maxheld83** [comment]
@jhoeffler sorry also cannot reproduce this issue -- the data should be exactly the same as previously.

A possible difference is that the old dashboard (soon to be deprecated in #58) already has the 2020 update, but https://subugoe.github.io/hoad/ does not.
But I did not otherwise edit the data sources.

AFAIK, there is only one SAGE journal on https://subugoe.shinyapps.io/hybridoa/, "Peacebuilding ..." something, so I am guessing this is new in the 2020 update.

I'll check back here once I've merged the 2020 update in #172

**Comment by jhoeffler** [comment]
The refactored dashboard version at https://subugoe.github.io/hoad/articles/interactive.html is based on data from around end of 2019, that’s why SAGE publications cannot be selected, there was still no open access license data for it in the CrossRef database.

The version available at https://subugoe.shinyapps.io/hybridoa/ seems to be based on data from update_jan_feb_20, when there was still very little data on SAGE open access licenses in the CrossRef database.

Just replacing hybrid_publications.csv in the refactored dashboard version with the jan_feb_20 update stored at https://github.com/subugoe/hoad/blob/update_jan_feb_20/data/hybrid_publications.csv?raw=true does not work (Max mentioned he could not reproduce the dashboard with that data version) as the columns domain and suffix are missing that are needed for the dashboard. Adding just empty columns for them allows to run the dashboard but with an error.

Updating the dashboard with the April 2020 data available at https://github.com/subugoe/hoad/blob/2020_update/data/hybrid_publications.csv?raw=true shows more SAGE journals as licenses indicating open access also for previous years were deposited to CrossRef only after February 2020.

**Comment by njahn82** [comment]
https://subugoe.shinyapps.io/hybridoa/    was deployed using this release:
https://github.com/subugoe/hoad/releases/tag/v0.2

https://najkoja.shinyapps.io/hybridoa/ shows the current state of the
2020_update branch.

**Comment by maxheld83** [comment]
I'll revisit this once I've merged the 2020 data #172

**Comment by njahn82** [comment]
I don't think this is needed, there's just a confusion about the different data versions.

**Comment by maxheld83** [comment]
thanks!
 As expected, with #172 merged in , the issue is resolved in https://github.com/subugoe/hoad/commit/a10518e1f4ad7064750b900accc3636ad477cd9a.

Can confirm that SAGE is now also on http://subugoe.github.io/hoad/.
