### ISSUE TITLE
List of used datasets incomplete

### ISSUE THREAD

**Issue by jhoeffler** [subugoe/hoad#201]
For example, Unpaywall, Dissemin missing in data description at https://github.com/subugoe/hoad/blob/2020_update/data/README.Rmd

**Comment by maxheld83** [comment]
yes!
We should add and document those data sources once we document the data objects in which they are actually used, as in, for example, https://subugoe.github.io/hoad/reference/hybrid_publications.html.

**Comment by maxheld83** [comment]
dissemin is now mentioned, and I think so are most of the data sources in the old `data/README.md`, but this will be an ongoing effort as we factor out ever more code from the scripts.

**Comment by njahn82** [comment]
Dissemin is not used as a data source. Part of its source code is used for
the licence matching.

Max Held <notifications@github.com> schrieb am Do., 4. Juni 2020, 08:35:

**Comment by maxheld83** [comment]
right, sorry, that's what I meant.
That's how it's documented: https://subugoe.github.io/hoad/reference/license_patterns.html

**Comment by jhoeffler** [comment]
They compiled, as is now correclty described, "a list of licenses used in Crossref, which indicate OA availability". A list is data, not code.
