### ISSUE TITLE
Re-direct about

### ISSUE THREAD

**Issue by njahn82** [subugoe/hoad#273]
https://subugoe.github.io/hybrid_oa_dashboard/about.html needs to be re-directed to https://subugoe.github.io/hoad/articles/about.html

It has been cited several times:
https://scholar.google.com/scholar?hl=de&as_sdt=0%2C5&q=https%3A%2F%2Fsubugoe.github.io%2Fhybrid_oa_dashboard%2F+about.html&btnG=

**Comment by maxheld83** [comment]
just to be clear https://subugoe.github.io/hybrid_oa_dashboard/about.html  *was* forwarded, just to root, not /articles/about.html (now fixed).

I think we should, in future, avoid giving out links to sub-subdirectories as much as possible (https://subugoe.github.io/hoad/articles/about.html) and stick to https://subugoe.github.io/hoad/ (which should eventually become open.sub.uni-goettingen.de/hoad as per https://github.com/subugoe/subugoe.github.io/issues/3).

We *can* make a guarantee that some landing page will continue to work, and that visitors can find the desired source from there.
But I don't think we can make guarantees about subdirectories.
It's bad, but these may change for any number of reasons that we can't keep track of.
Or we just register a DOI for the material in question ☺️.

**Comment by njahn82** [comment]
cool, thanks
