### ISSUE TITLE
publish to ghpages branch, not docs/

### ISSUE THREAD

**Issue by maxheld83** [subugoe/hoad#37]
`docs/` can be convenient, but has a some disadvantages:

- bloats the repo
- does not play nice with ci/cd

**Comment by njahn82** [comment]
Can't find the files needed to generate about.html, especially `about.Rmd`. Where can I find them?

**Comment by njahn82** [comment]
Found them in the the refactor-as-pkg branch!

**Comment by maxheld83** [comment]
argh, yes, sorry about that @njahn82 https://github.com/subugoe/hybrid_oa_dashboard/commit/8e1e50d9403ec90a94c699e51919a46aeb1c0418 was an unclean commit, I shouldn't have deleted *all* of `/docs`.

Will be rectified once `refactor-as-pkg` gets merged next week.
